name: Deployment Pipeline

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up your environment (install dependencies, etc.)
      - name: Set up Node.js (or your language/environment)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the appropriate version for your stack

      # Step 3: Run your deployment script (replace with your actual deploy script)
      - name: Run Deployment Script
        run: |
          ./deploy.sh
          
      # Step 4: Capture deployment quality rate (Success/Failure)
      - name: Capture Deployment Quality Rate
        id: quality-rate
        run: |
          if [ $? -eq 0 ]; then
            echo "Deployment Quality Rate: 100% (Success)" >> $GITHUB_ENV
          else
            echo "Deployment Quality Rate: 0% (Failure)" >> $GITHUB_ENV
            exit 1  # Exit with failure status to trigger rollback
          fi

      # Step 5: Generate JSON logs on success
      - name: Generate Success Log (JSON)
        if: success()  # Only runs if previous steps succeeded
        run: |
          echo "{\"status\": \"success\", \"deployment_quality_rate\": \"100%\", \"timestamp\": \"$(date)\"}" > deployment_logs.json

      # Step 6: Upload logs as an artifact if successful
      - name: Upload Success Artifact
        if: success()  # Only runs if previous steps succeeded
        uses: actions/upload-artifact@v2
        with:
          name: deployment-logs
          path: deployment_logs.json

      # Step 7: Trigger rollback in case of failure
      - name: Trigger Rollback (Failure)
        if: failure()  # Runs only if the pipeline fails
        run: |
          echo "Deployment failed. Triggering rollback..."
          ./rollback.sh

      # Step 8: Upload previous version artifact (for rollback)
      - name: Upload Previous Deployment Artifact
        if: failure()  # Only runs if rollback is triggered
        uses: actions/upload-artifact@v2
        with:
          name: previous-deployment
          path: ./previous_version_directory/  # Adjust path to where backup/artifacts are stored
